version: '3'


services:

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        expose:
            - 27017

    web:
        build: .
        command:
            python manage.py runserver 0.0.0.0:8000
            #gunicorn prevadoproj.wsgi:application --bind 0.0.0.0:8000
        ports:
            - 8000:8000
        links:
            - mongodb
        depends_on:
            - mongodb
        volumes:
            - .:/app
